module RDF
  # Taken from the XML file bibo.php at http://purl.org/ontology/bibo/
  class Bibo < Vocabulary("http://purl.org/ontology/bibo/")
    property :affirmedBy
    property :annotates
    property :authorList
    property :citedBy
    property :cites
    property :contributorList
    property :court
    property :degree
    property :director
    property :distributor
    property :editor
    property :editorList
    property :interviewee
    property :interviewer
    property :issuer
    property :organizer
    property :owner
    property :performer
    property :presentedAt
    property :presents
    property :producer
    property :recipient
    property :reproducedIn
    property :reversedBy
    property :reviewOf
    property :status
    property :subsequentLegalDecision
    property :transcriptOf
    property :translationOf
    property :translator
    property :abstract
    property :argued
    property :asin
    property :chapter
    property :coden
    property :content
    property :doi
    property :eanucc13
    property :edition
    property :eissn
    property :gtin14
    property :handle
    property :identifier
    property :isbn
    property :isbn10
    property :isbn13
    property :issn
    property :issue
    property :lccn
    property :locator
    property :numPages
    property :numVolumes
    property :number
    property :oclcnum
    property :pageEnd
    property :pageStart
    property :pages
    property :pmid
    property :prefixName
    property :section
    property :shortDescription
    property :shortTitle
    property :sici
    property :suffixName
    property :upc
    property :uri
    property :volume

    # RDF::Vocabulary doesn't seem to support classes explicitly, and I didn't
    # see any examples of using `property` for this, so I've just ignored them

    # AcademicArticle
    # Article
    # AudioDocument
    # AudioVisualDocument
    # Bill
    # Book
    # BookSection
    # Brief
    # Chapter
    # Code
    # CollectedDocument
    # Collection
    # Conference
    # CourtReporter
    # Document
    # DocumentPart
    # DocumentStatus
    # EditedBook
    # Email
    # Event
    # Excerpt
    # Film
    # Hearing
    # Image
    # Interview
    # Issue
    # Journal
    # LegalCaseDocument
    # LegalDecision
    # LegalDocument
    # Legislation
    # Letter
    # Magazine
    # Manual
    # Manuscript
    # Map
    # MultiVolumeBook
    # Newspaper
    # Note
    # Patent
    # Performance
    # Periodical
    # PersonalCommunication
    # PersonalCommunicationDocument
    # Proceedings
    # Quote
    # ReferenceSource
    # Report
    # Series
    # Slide
    # Slideshow
    # Standard
    # Statute
    # Thesis
    # ThesisDegree
    # Webpage
    # Website
    # Workshop
  end
end